### ISSUE TITLE
example project does not run on linux🐛 

### ISSUE THREAD

**Issue by solaristhesun** [bdlukaa/fluent_ui#190]
```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method SystemTheme.accentColor on channel system_theme)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      SystemAccentColor.load (package:system_theme/system_theme.dart:93:18)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method Initialize on channel com.alexmercerind/flutter_acrylic)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      Window.initialize (package:flutter_acrylic/flutter_acrylic.dart:75:5)
<asynchronous suspension>
#2      main (package:example/main.dart:40:5)
<asynchronous suspension>
```

**Comment by solaristhesun** [comment]
Thanks @bdlukaa for the quick response. However it is still not working for me. It looks like there are two issues: one with SystemTheme.accentColor (which seems to be solved) and another one with flutter_acrylic.

```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method Initialize on channel com.alexmercerind/flutter_acrylic)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      Window.initialize (package:flutter_acrylic/flutter_acrylic.dart:75:5)
<asynchronous suspension>
#2      main (package:example/main.dart:46:5)
<asynchronous suspension>
```
