### ISSUE TITLE
🐛 No FluentLocalizations found.

### ISSUE THREAD

**Issue by RealHeart** [bdlukaa/fluent_ui#377]
**Describe the bug**

```
The following assertion was thrown while handling a gesture:
No FluentLocalizations found.
MyApp widgets require FluentLocalizations to be provided by a Localizations widget ancestor.
The fluent library uses Localizations to generate messages, labels, and abbreviations.
To introduce a FluentLocalizations, either use a FluentApp at the root of your application to
include them automatically, or add a Localization widget with a FluentLocalizations delegate.
```

**To Reproduce**

Click Button

code:
```dart
import 'package:fluent_ui/fluent_ui.dart';
import 'package:system_theme/system_theme.dart';

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<StatefulWidget> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  int index = 0;

  @override
  Widget build(BuildContext context) {
    return FluentApp(
      localizationsDelegates: const [
        DefaultFluentLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'),
        Locale('zh'),
      ],
      locale: const Locale('zh'),
      theme: ThemeData(
        accentColor: Colors.blue,
        brightness: SystemTheme.isDarkMode ? Brightness.dark : Brightness.light,
      ),
      home: NavigationView(
        appBar: const NavigationAppBar(title: Text("Fluent Design App Bar")),
        pane: NavigationPane(
          selected: index,
          onChanged: (i) => setState(() => index = i),
          displayMode: PaneDisplayMode.auto,
          items: [
            PaneItem(
                icon: const Icon(FluentIcons.code),
                title: const Text("Sample Page 1")),
            PaneItem(
                icon: const Icon(FluentIcons.user_window),
                title: const Text("Sample Page 2"))
          ],
        ),
        content: NavigationBody(
          index: index,
          children: [
            ScaffoldPage(
              header: const Text(
                "Sample Page 1",
                style: TextStyle(fontSize: 60),
              ),
              content: Center(
                child: Button(
                  child: const Text("Click Me!"),
                  onPressed: () {
                    showDialog(
                        context: context,
                        builder: (context) {
                          return const ContentDialog(
                            title: Text("This is a content dialog"),
                            content: Text(
                                "Dialogs are modal UI overlays that provide contextual app information. They block interactions with the app window until being explicitly dismissed. They often request some kind of action from the user."),
                          );
                        });
                  },
                ),
              ),
            ),
            const ScaffoldPage(),
          ],
        ),
      ),
    );
  }
}

```

**Expected behavior**

**Screenshots**

**Additional context**

```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
No FluentLocalizations found.
MyApp widgets require FluentLocalizations to be provided by a Localizations widget ancestor.
The fluent library uses Localizations to generate messages, labels, and abbreviations.
To introduce a FluentLocalizations, either use a FluentApp at the root of your application to
include them automatically, or add a Localization widget with a FluentLocalizations delegate.
The specific widget that could not find a FluentLocalizations ancestor was:
  MyApp
The ancestors of this widget were:
  ...
  [root]

When the exception was thrown, this was the stack:
#0      debugCheckHasFluentLocalizations.<anonymous closure> (package:fluent_ui/src/utils.dart:52:7)
#1      debugCheckHasFluentLocalizations (package:fluent_ui/src/utils.dart:73:4)
#2      showDialog (package:fluent_ui/src/controls/surfaces/dialog.dart:229:10)
#3      _MyAppState.build.<anonymous closure> (package:grasscutter_tools/app.dart:56:21)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
#7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:269:7)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:449:20)
#10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
#11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
#12     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
#13     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#19     _invoke1 (dart:ui/hooks.dart:170:10)
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 3 frames from dart:async)

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#3385d
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by henry2man** [comment]
Hi there @RealHeart!
This looks weird, `zh` localization is included in latest `3.12.0`. What version of FluentUI are you using ?

**Comment by RealHeart** [comment]
> Hi there @RealHeart! This looks weird, `zh` localization is included in latest `3.12.0`. What version of FluentUI are you using ?

3.12.0

**Comment by henry2man** [comment]
Ok, so it seems like a valid issue, but I'm not sure why this is happening.

**Comment by bdlukaa** [comment]
```dart
showDialog( context: context, builder: (context) { return const ContentDialog( title: Text("This is a content dialog"), content: Text( "Dialogs are modal UI overlays that provide contextual app information. They block interactions with the app window until being explicitly dismissed. They often request some kind of action from the user."), ); });
```

the showDialog function is using the context from the buildFunction. Wrap your button in a `Builder` and it should work fine

**Comment by bdlukaa** [comment]
Closing as resolved
