### ISSUE TITLE
🐛 TabView: RangeError (index): Invalid value: Not in inclusive range 0..2: 3

### ISSUE THREAD

**Issue by jonahzheng** [bdlukaa/fluent_ui#426]
![QQQ](https://user-images.githubusercontent.com/5125282/179373902-32df542e-7cd5-4744-b279-dab31747f527.gif)

```
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
Debug service listening on ws://127.0.0.1:61072/Badi2rcO9tY=/ws
Syncing files to device Windows...

======== Exception caught by widgets library =======================================================
The following RangeError was thrown building TabView(currentIndex: 3, addIconData: IconData(U+0E710), tabs: 3, dirty, dependencies: [_LocalizationsScope-[GlobalKey#27e83], _FluentTheme, Directionality], state: _TabViewState#9420c):
RangeError (index): Invalid value: Not in inclusive range 0..2: 3

The relevant error-causing widget was: 
  TabView TabView:file:///D:/flutter_prj/fluent_ui/example/lib/screens/navigation/tab_view.dart:51:18
When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      _TabViewState.build (package:fluent_ui/src/controls/navigation/tab_view.dart:496:38)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#16     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#20     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#28     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#32     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#35     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#37     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#41     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#43     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1265:37)
#44     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1169:35)
#45     Iterable.forEach (dart:core/iterable.dart:325:35)
#46     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1213:24)
#47     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1146:7)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#51     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#52     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#53     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:237:11)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#64     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#66     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#68     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#72     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#74     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#78     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#80     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#82     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#84     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#86     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#88     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#91     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#93     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#95     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#99     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#103    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#106    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#107    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#108    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#111    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#113    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#116    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#117    StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#121    StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#125    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#126    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#127    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#128    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#130    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#132    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#133    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#135    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#136    StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#137    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#139    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#140    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#142    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#143    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#147    StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#148    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#150    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#151    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#152    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#153    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#154    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#155    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#156    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#157    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#161    _invoke (dart:ui/hooks.dart:151:10)
#162    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#163    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================

```

flutter
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [版本 10.0.19044.1826], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.8)
[√] Android Studio (version 2021.1)
[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
[√] VS Code, 64-bit edition (version 1.65.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

```

**Comment by bdlukaa** [comment]
What version are you using?

**Comment by jonahzheng** [comment]
@bdlukaa 
origin/master
