### ISSUE TITLE
🐛   Unhandled Exception: Failed assertion: line 168 pos 12: '_overlay != null': is not true.

### ISSUE THREAD

**Issue by TENX-S** [bdlukaa/fluent_ui#955]
**Describe the bug**
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 168 pos 12: '_overlay != null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:168:12)
#3      displayInfoBar.<anonymous closure>.<anonymous closure>.close (package:fluent_ui/src/controls/surfaces/info_bar.dart:62:40)
<asynchronous suspension>
```

**To Reproduce**
1. call displayInfoBar()
2. go to another screen (In macOS desktop, just swipe the touchpad)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bdlukaa** [comment]
This is very weird, since we check [if the entry is mounted](https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/surfaces/info_bar.dart#L62) before removing it. I can not reproduce this locally
